apiVersion: v1
kind: Service
metadata:
  name: zookeeper-svc
  namespace: fintech
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: fintech-mvp
    app.kubernetes.io/component: messaging
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: client
      protocol: TCP
