global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: 'transaction-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['transaction-service:8080']

  - job_name: 'account-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['account-service:8081']
