server:
  port: 8082

spring:
  application:
    name: transaction-service

  # Conexão com o banco fintech-postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/fintech
    username: fintech_admin
    password: fintech_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Valida contra o schema que criamos manualmente
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # Parâmetros do Cluster Kafka local
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      group-id: fintech-tx-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

# Exposição Actuator para raspagem do Prometheus
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  metrics:
    export:
      prometheus:
        enabled: true
