apiVersion: v1
kind: ConfigMap
metadata:
  name: fintech-app-config
  namespace: fintech
  labels:
    app.kubernetes.io/part-of: fintech-mvp
data:
  # ── PostgreSQL ──────────────────────────────────────────────────────────────
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-svc:5432/fintech"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"

  # ── Kafka ────────────────────────────────────────────────────────────────────
  # Endereço interno do broker dentro do namespace fintech
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka-svc:29092"

  # ── Observabilidade ──────────────────────────────────────────────────────────
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_OTLP_TRACING_ENDPOINT: "http://jaeger-svc:4318/v1/traces"
